--------------------------------------------------------
--  DDL for HYDRA_CURRICULUM TABLE AND CURRICULUM_ID_SEQUENCE
--------------------------------------------------------
--In case a table needs to be created. Commented out because it creates more problems than it solves.
DROP TABLE IF EXISTS HYDRA_CURRICULUM;
CREATE TABLE IF NOT EXISTS HYDRA_CURRICULUM (CURRICULUM_ID INT(11) PRIMARY KEY, CURRICULUM_NAME VARCHAR(20));
DROP SEQUENCE IF EXISTS CURRICULUM_ID_SEQUENCE;
CREATE SEQUENCE  IF NOT EXISTS  CURRICULUM_ID_SEQUENCE  MINVALUE 1  INCREMENT BY 1 START WITH 1;



Insert into HYDRA_CURRICULUM (CURRICULUM_ID, CURRICULUM_NAME) values (1, 'JTA');
Insert into HYDRA_CURRICULUM (CURRICULUM_ID, CURRICULUM_NAME) values (2, 'JAVA');
Insert into HYDRA_CURRICULUM (CURRICULUM_ID, CURRICULUM_NAME) values (3, '.NET');
Insert into HYDRA_CURRICULUM (CURRICULUM_ID, CURRICULUM_NAME) values (4, 'PEGA');
Insert into HYDRA_CURRICULUM (CURRICULUM_ID, CURRICULUM_NAME) values (5, 'DynamicCRM');
Insert into HYDRA_CURRICULUM (CURRICULUM_ID, CURRICULUM_NAME) values (6, 'SalesForce');
Insert into HYDRA_CURRICULUM (CURRICULUM_ID, CURRICULUM_NAME) values (7, 'MicroService');
Insert into HYDRA_CURRICULUM (CURRICULUM_ID, CURRICULUM_NAME) values (8, 'SEED');
Insert into HYDRA_CURRICULUM (CURRICULUM_ID, CURRICULUM_NAME) values (9, 'Oracle Fusion');